# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
#  - name: About me
#    url: "about/#about"
#    weight: 10
  - name: Digital garden  # A link title for your page.
    url: "post/"  # The URL of your page.
    weight: 10  # The position of your page in the menu.
#  - name: Recent Posts
#    url: '#posts'
#    weight: 20
#  - name: Tags
#    url: '#tags'
#    weight: 20
#   - name: Projects
#     url: '#projects'
#     weight: 30
#   - name: Talks
#     url: '#talks'
#     weight: 40
#   - name: Publications
#     url: '#featured'
#     weight: 50
#   - name: Courses
#     url: courses/
#     weight: 60
#   - name: Contact
#     url: '#contact'
#     weight: 70
